kind: pipeline
type: docker
name: default

steps:
  - name: install
    image: node
    commands:
      - cd mocha_instanbul
      - npm install
  - name: test
    image: node
    commands:
      - cd mocha_instanbul
      - npm test
  - name: upload
    image: covergates/drone-covergates
    settings:
      report_id: bt9huh223akg00dkqseg
      report: ./coverage/lcov.info
      type: lcov
      comment: true
    when:
      event:
        - pull_request
